stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  tags:
    - docker
    - java
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  only:
    - merge_requests
    - dev

unit-test:
  stage: test
  tags:
    - docker
    - java
  script:
    - mvn test
  only:
    - merge_requests
    - dev