
stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

image: docker:24.0

services:
  - name: docker:24.0-dind
    alias: docker

before_script:
  - apk add --no-cache openjdk21 maven
  - docker-compose -f docker-compose.yml up -d

test:
  stage: test
  script:
    - mvn test -Dspring.active.profiles=test
  tags:
    - docker
    - java


build:
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
  tags:
    - docker
    - java

after_script:
  - docker-compose -f docker-compose.yml down -v
