stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  POSTGRES_DB: testdb
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpass
  SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/${POSTGRES_DB}
  SPRING_REDIS_HOST: localhost
  SPRING_PROFILES_ACTIVE: test


cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  image: maven:3.9-eclipse-temurin-21
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  only:
    - merge_requests
    - dev
  tags:
    - docker
    - java

#test:
#  stage: test
#  image: maven:3.9-eclipse-temurin-21
#  services:
#    - name: docker:dind
#      alias: docker
#    - name: redis:7-alpine
#      alias: redis
#  variables:
#    DOCKER_HOST: tcp://docker:2375
#    TESTCONTAINERS_RYUK_DISABLED: "true"
#    TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX: "docker.io/"
#    SPRING_REDIS_HOST: redis
#    SPRING_PROFILES_ACTIVE: test
#  script:
#    - mvn test -Dspring.profiles.active=test -Dtestcontainers.reuse.enable=true
#  only:
#    - merge_requests
#    - dev
#  tags:
#    - docker
#    - java


test:
  stage: test
  image: docker:24.0
  services:
    - name: docker:24.0-dind
      alias: docker
  variables:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ""
  script:
    - export DOCKER_HOST=tcp://localhost:2375
    - apk add --no-cache postgresql-client redis openjdk17 maven

    - docker run -d --name postgres 
      -e POSTGRES_DB=$POSTGRES_DB 
      -e POSTGRES_USER=$POSTGRES_USER 
      -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD 
      -p 5433:5432 
      postgres:15-alpine

    - docker run -d --name redis -p 6379:6379 redis:7-alpine

    - timeout 60 sh -c 'until pg_isready -h localhost -p 5433 -U $POSTGRES_USER -d $POSTGRES_DB; do sleep 1; done'
    - timeout 60 sh -c 'until redis-cli -h localhost ping | grep -q "PONG"; do sleep 1; done'

    - mvn test
    - docker stop postgres redis || true
    - docker rm postgres redis || true
  only:
    - merge_requests
    - dev
  tags:
    - docker
    - java