stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

services:
  - name: docker:dind
    alias: docker

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  image: maven:3.9-eclipse-temurin-21
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  only:
    - merge_requests
    - dev
  tags:
    - docker
    - java

test:
  stage: test
  image: maven:3.9-eclipse-temurin-21
  services:
    - name: docker:dind
      alias: docker
    - name: redis:7-alpine
      alias: redis
  variables:
    DOCKER_HOST: tcp://docker:2375
    TESTCONTAINERS_RYUK_DISABLED: "true"
    TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX: "docker.io/"
    SPRING_REDIS_HOST: redis
    SPRING_PROFILES_ACTIVE: test
  script:
    - mvn test -Dspring.profiles.active=test -Dtestcontainers.reuse.enable=true
  only:
    - merge_requests
    - dev
  tags:
    - docker
    - java