stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  POSTGRES_DB: testdb
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpass
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-todo:5432/${POSTGRES_DB}
  SPRING_REDIS_HOST: redis
  SPRING_PROFILES_ACTIVE: test
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  TESTCONTAINERS_RYUK_DISABLED: "true"


cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  image: maven:3.9-eclipse-temurin-21
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  only:
    - merge_requests
    - dev
  tags:
    - docker
    - java

#test:
#  stage: test
#  image: maven:3.9-eclipse-temurin-21
#  services:
#    - name: docker:dind
#      alias: docker
#    - name: redis:7-alpine
#      alias: redis
#  variables:
#    DOCKER_HOST: tcp://docker:2375
#    TESTCONTAINERS_RYUK_DISABLED: "true"
#    TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX: "docker.io/"
#    SPRING_REDIS_HOST: redis
#    SPRING_PROFILES_ACTIVE: test
#  script:
#    - mvn test -Dspring.profiles.active=test -Dtestcontainers.reuse.enable=true
#  only:
#    - merge_requests
#    - dev
#  tags:
#    - docker
#    - java


test:
  stage: test
  image: docker:24.0
  services:
    - name: docker:24.0-dind
      alias: docker
  script:
    - apk add --no-cache docker-compose postgresql-client redis openjdk21 maven
    - unset DOCKER_HOST
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker network create test-network
    - docker run -d --name postgres-todo --network test-network 
      -e POSTGRES_DB=$POSTGRES_DB 
      -e POSTGRES_USER=$POSTGRES_USER 
      -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD 
      -p 5432:5432
      postgres:15-alpine
    - docker run -d --name redis --network test-network 
      redis:7-alpine
    - timeout 120 sh -c 'until docker exec postgres-todo pg_isready -U $POSTGRES_USER -d $POSTGRES_DB; do sleep 2; echo "Waiting..."; done'
      # Ожидание Redis
      - timeout 30 sh -c 'until docker exec redis redis-cli ping | grep -q "PONG"; do sleep 1; done'
    - docker run --rm --network test-network 
      -v $(pwd):/app -w /app 
      -e SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL 
      -e SPRING_REDIS_HOST=redis 
      maven:3.9-eclipse-temurin-21 
      mvn test -Dspring.profiles.active=test
  after_script:
    - unset DOCKER_HOST
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker stop postgres-todo redis || true
    - docker rm postgres-todo redis || true
    - docker network rm test-network || true
  only:
    - merge_requests
    - dev
  tags:
    - docker
    - java