stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  POSTGRES_DB: testdb
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpass
  SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
  SPRING_REDIS_HOST: redis
  SPRING_PROFILES_ACTIVE: test
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  TESTCONTAINERS_RYUK_DISABLED: "true"

services:
  - name: docker:24.0-dind
    alias: docker

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  image: maven:3.9-eclipse-temurin-21
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  only:
    - merge_requests
    - dev
  tags:
    - docker
    - java

#test:
#  stage: test
#  image: maven:3.9-eclipse-temurin-21
#  services:
#    - name: docker:dind
#      alias: docker
#    - name: redis:7-alpine
#      alias: redis
#  variables:
#    DOCKER_HOST: tcp://docker:2375
#    TESTCONTAINERS_RYUK_DISABLED: "true"
#    TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX: "docker.io/"
#    SPRING_REDIS_HOST: redis
#    SPRING_PROFILES_ACTIVE: test
#  script:
#    - mvn test -Dspring.profiles.active=test -Dtestcontainers.reuse.enable=true
#  only:
#    - merge_requests
#    - dev
#  tags:
#    - docker
#    - java


test:
  stage: test
  script:
    - apk add --no-cache docker-compose openjdk21 maven
    - unset DOCKER_HOST
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker compose -f docker-compose.test.yml up -d
    - mvn test
  after_script:
    - unset DOCKER_HOST
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker compose -f docker-compose.test.yml down -v
  only:
    - merge_requests
    - dev
  tags:
    - docker
    - java