image: docker:24.0

stages:
  - test
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  COMPOSE_PROJECT_NAME: "springtodo_ci_${CI_PIPELINE_ID}"

services:
  - name: docker:24.0-dind
    alias: docker

before_script:
  - apk add --no-cache curl bash openjdk21 maven git
  - docker-compose -f docker-compose.yml up -d

test:
  stage: test
  script:
    - mvn test

build:
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar

after_script:
  - docker-compose down -v
