CREATE TABLE IF NOT EXISTS todos (
id BIGSERIAL PRIMARY KEY,
title VARCHAR(100) NOT NULL,
description VARCHAR(500),
completed BOOLEAN DEFAULT FALSE,
created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);