concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "emrunner"
  url = "https://gitlab.com"
  id = 47477323
  token = "glrt-gQM-uKMEk3FETsh5Bl8WnW86MQpwOjE1bWNyNwp0OjMKdTpka2Npdhg.01.1j1ywp7m0"
  token_obtained_at = 2025-05-16T12:52:42Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "maven:3.8.6-openjdk-17"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0
    network_mtu = 0
